### ISSUE TITLE
satisfying org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### ISSUE THREAD

**Issue by matthewkooshad** [frgmt/flutter-sqlite-viewer#1]
in android\build.gradle, i have ext.kotlin_version = '1.3.50'

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':sqlite_viewer' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

i would like to use this plugin, but how can i with my current kotlin version? thanks

**Comment by AndresGarciaSobrado91** [comment]
same issue

**Comment by giri-jeedigunta** [comment]
+ 1

**Comment by FloPMT** [comment]
Forked and fixed. Feel free to use:
https://github.com/FloPMT/flutter-sqlite-viewer

In pubspec.yaml:
`sqlite_viewer:
    git: git://github.com/FloPMT/flutter-sqlite-viewer.git`

**Comment by frgmt** [comment]
@giri-jeedigunta Thanks for fixing. If you send PR, I want to merge it.

**Comment by giri-jeedigunta** [comment]
> @giri-jeedigunta Thanks for fixing. If you send PR, I want to merge it.

I didn't fix it :) @FloPMT fixed it. 
Can you please a raise a PR for this Repo so this could get published into the dart packages. 

Thank you !

**Comment by FloPMT** [comment]
Just did: https://github.com/frgmt/flutter-sqlite-viewer/pull/2

**Comment by frgmt** [comment]
@giri-jeedigunta oops, sorry..

**Comment by giri-jeedigunta** [comment]
Thanks @FloPMT @frgmt 👍✌️

**Comment by matthewkooshad** [comment]
@frgmt since it's in master  now, i would expect to be using it with this line i just put into my dependencies just now: 
`sqlite_viewer: `

i ran `flutter packages get`.
is there something more i should be doing to use it?

**Comment by frgmt** [comment]
@matthewkooshad now, I updated package version. so, maybe you just should do `flutter packages upgrade`.  and you may need `flutter clean` first.

**Comment by matthewkooshad** [comment]
that didn't work, so i tried to specify 1.0.3, but then i got this error of that the app depends on sqlite_viewer 1.0.3 which doesn't match any versions, version solving failed. so, i think there's some place that `flutter pub get` is looking at for the version of your package, which hasn't received your update of what the current version is yet.

**Comment by frgmt** [comment]
@matthewkooshad sorry, I haven't used flutter for a long time. now, I uploaded into pub.dev site. so maybe, you can do `flutter pub get`.
https://pub.dev/packages/sqlite_viewer
