### ISSUE TITLE
please upgrade to support null-safety

### ISSUE THREAD

**Issue by born2pair** [frgmt/flutter-sqlite-viewer#5]
As dart 2.12 released recently, the official dart team encourages all packages upgrade to support null-safety property asap, before app which uses these packages can upgrade.

Thank you!

**Comment by kirill09** [comment]
The code has already been updated, it just hasn't been published in pub.
You can use a solution like this:
sqlite_viewer: 
    git: 
      url: https://github.com/frgmt/flutter-sqlite-viewer.git
